# fly.toml app configuration file generated for vxu-api-docs on 2023-08-25T20:35:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vxu-api-docs"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
